spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lms
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: lmsSystem3695@gmail.com
    password: system!@34
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace